### ISSUE TITLE
Segmentation Fault - Single-Player

### ISSUE THREAD

**Issue by VencaCZ** [alphaonex86/CatchChallenger#10]
After compiling latest code I got this error on Linux when I try to start game

`
QEventLoop: Cannot be used without QApplication
"GCC 5.4.0 build: Feb 18 2017 23:09:22"
"Qt version: 5.5.1 (328961)"
QObject::connect: invalid null parameter
QGraphicsScene::addItem: item has already been added to this scene
Audio volume set to:  100
QObject::connect: invalid null parameter
QObject::connect: invalid null parameter
QObject::connect: invalid null parameter
QObject::connect: invalid null parameter
QObject::connect: invalid null parameter
QObject::connect: invalid null parameter
`

**Comment by alphaonex86** [comment]
Hello, to fix a Segmentation Fault, I need a backtrace or the exact step to reproduce the error.

**Comment by VencaCZ** [comment]
cd client/single-player
qmake *.pro
make -j24
./catchchallenger-single-player

and then that error (yes i have data files )
works without problems with latest commit that I had with my make it work on linux changes (commit SHA 09f54da8280f3ee0e3a03915e1b4ae314fa1f783)

**Comment by alphaonex86** [comment]
Fixed into the last commit
