### ISSUE TITLE
Segmentation Fault - Single player

### ISSUE THREAD

**Issue by VencaCZ** [alphaonex86/CatchChallenger#11]
cd client/single-player
qmake *.pro
make -j24
./catchchallenger-single-player
new-game
name it test

crash

QEventLoop: Cannot be used without QApplication
"GCC 5.4.0 build: Feb 18 2017 22:46:35"
"Qt version: 5.5.1 (328961)"
QObject::connect: invalid null parameter
QGraphicsScene::addItem: item has already been added to this scene
Audio volume set to:  100
The loading file sound not exists:  "/home/venca/CatchChallenger/client/single-player/music/loading.opus"
Connected to SQLite at /home/venca/.local/share/CatchChallenger/client-single-player/savegames/0/catchchallenger.db.sqlite
Connected to SQLite at /home/venca/.local/share/CatchChallenger/client-single-player/savegames/0/catchchallenger.db.sqlite
Connected to SQLite at /home/venca/.local/share/CatchChallenger/client-single-player/savegames/0/catchchallenger.db.sqlite
Connected to SQLite at /home/venca/.local/share/CatchChallenger/client-single-player/savegames/0/catchchallenger.db.sqlite
Preload data for server version 2.0.1.3
Datapack, base: /home/venca/CatchChallenger/client/single-player/datapack/
4 skin(s) loaded
2 reputation(s) loaded
9 monster buff(s) loaded
14 type(s) loaded
76 items(s) loaded
3 trap(s) loaded
11 plant(s) loaded
8 crafting recipe(s) loaded
46 monster skill(s) loaded
1 event(s) loaded
43 monster(s) loaded
5 monster(s) collisions loaded
7 monster evolution items(s) loaded
1 monster items(s) to learn loaded
0 industries loaded
0 industries link loaded
1 profile(s) loaded
layers options parsed
19 quest(s) loaded
157 bot fight(s) loaded
6 monster items(s) to learn loaded
1 server profile(s) loaded
0 industries loaded (spec industries 13)
0 industries link loaded (spec industries link 13)
Loaded the common datapack into 9ms
440 file for datapack loaded base, 434 file for datapack loaded main, 0 file for datapack loaded sub
EBEDF5D7706045DE60CC456E1206DBE1B37B370F813D2507F3BAFD0C hash for datapack loaded base, 531781383CE6C4198123CBAF8E2A0FEA5EE5FB7CC6BD170B3C981A95 hash for datapack loaded main,  hash for datapack loaded sub
4 skin(s) loaded
43 monster drop(s) loaded
/home/venca/CatchChallenger/client/single-player/datapack/map/main/official/castel-town/-3.3.xml, Parse error at line 5 column 50: Error reading Attributes.
5 learn point(s) on map loaded
2 zonecapture point(s) on map loaded
16 heal point(s) on map loaded
0 market point(s) on map loaded
164 bot fight(s) on map loaded
571 bot fights tigger(s) on map loaded
10 shop(s) on map loaded
347 bots(s) on map loaded
171 map(s) loaded
File excluded because don't match the regex (4): items/catchtrap/1_failed.xcf
File excluded because don't match the regex (4): items/catchtrap/1_success.xcf
File excluded because don't match the regex (4): items/catchtrap/catchtrap-traveling.xcf
File excluded because don't match the regex (4): monsters/essail.xcf
File excluded because don't match the regex (4): monsters/skill-animation/0.xcf
File excluded because don't match the regex (4): monsters/skill-animation/1.xcf
File excluded because don't match the regex (4): monsters/skill-animation/2.xcf
File excluded because don't match the regex (4): monsters/skill-animation/3.xcf
File excluded because don't match the regex (4): monsters/skill-animation/4.xcf
File excluded because don't match the regex (4): monsters/skill-animation/5.xcf
File excluded because don't match the regex (4): monsters/skill-animation/6.xcf
885 files for datapack loaded
342 SQL map dictionary
0 SQL item on map dictionary
Visibility: MapVisibilityAlgorithmSelection_None
0 zone(s) loaded
Loaded the server static datapack into 2076ms
0 SQL plant on map dictionary
Visibility: MapVisibilityAlgorithmSelection_None
0 zone(s) loaded
Loaded the server static datapack into 2ms
0 SQL industrie loaded
0 SQL monster list loaded
3 SQL reputation dictionary
5 SQL skin dictionary
1 profile loaded
0 SQL city loaded
1 SQL clan max id
0 SQL industries loaded
0 SQL plant on map
0 SQL market item
Loaded the server SQL datapack into 1676ms
protocolReplyCharacterList: 7F0E0000000201803A0900010114081E001E9600EBEDF5D7706045DE60CC456E1206DBE1B37B370F813D2507F3BAFD0C00
newConnection(): new client connected by fake socket
"Try auth: password b4ae2dbbbecfc862ac68764d6c3a09d6047299cc67337dfe62bfbc4c, token: 7c56cc2faa858825693eb1e0c61b523a, password+token acde3e22fd495f92ec0ccad6e64651b676efc1aa72f2ebb2f39e9f20 (b4ae2dbbbecfc862ac68764d6c3a09d6047299cc67337dfe62bfbc4c7c56cc2faa858825693eb1e0c61b523a) for the login: 3626d24e4136284ad1ecf9bd79d0ae9c0f0dd710a8adc7a09fe1a848"
"Try create account: login: 52a3935ad13d15776692fb0a48af46c6da9a7994a29bdd5e7ff85b55 and pass: b4ae2dbbbecfc862ac68764d6c3a09d6047299cc67337dfe62bfbc4c"
"For the character group 0 you don't have character"

**Comment by alphaonex86** [comment]
I have do another fix, work now?

**Comment by VencaCZ** [comment]
Now I have got to create character part but I got error Your pseudo can't contains space (pseudo is test without spaces)

**Comment by alphaonex86** [comment]
I continue working on it, the git version is tested only before publish it, sorry. This bug is fixed but I see more bug...

**Comment by VencaCZ** [comment]
That is ok I like your project so I do not mind testing it and looking for problems.

**Comment by alphaonex86** [comment]
Now should work. Git is my dev place, then the code is not fully stable in general

**Comment by VencaCZ** [comment]
Then you can make dev and master branch and work with it a little bit. :-)
