### ISSUE TITLE
Ingame problems (Linux) (Single Player)

### ISSUE THREAD

**Issue by VencaCZ** [alphaonex86/CatchChallenger#12]
- [x]  Prof Lignin (Starting town) I can not answer second question box ("Acts?") only thing that I am getting is parsed link to use:  "2 in command line
- [x] After trowing 50 iron traps at Conileaf Level 3 HP 1. I was not able to catch it.
- [x] 2 trainers at the end of Symposia has 2 monsters (LVL 15 and 18) with one monster you ned atlest LVL 22 and that takes ~35 minutes to grind. Their level should be lover if we consider that behind them are monsters lvl 7+ (Sugestion is LVL 7 and 10)
- [x] Iron Trap is over Priced with this Success chance
- [x] It should be possible to play without mouse
- [x] It would be nice to be able to press key for action based of it's name (For example N for Next, B for Bag, etc)
- [x] Chat has no use in Single player

**Comment by alphaonex86** [comment]
Some query is for the datapack https://github.com/alphaonex86/CatchChallenger-datapack/issues 
1) datapack
2) noted
3) datapack
4) datapack
5) what problem do you have to player without mouse?
6) noted
7) have multiple use, command, open to lan, ... you can collaspe it

**Comment by VencaCZ** [comment]
5. I need to use mouse to press some buttons and I would like to write support for controller.
7. Ok noted thank you

**Comment by alphaonex86** [comment]
5) what button, all should be accessible via tab and space/enter
