### ISSUE TITLE
Sugestion - Catching system - Dialog instead of "Traps"

### ISSUE THREAD

**Issue by VencaCZ** [alphaonex86/CatchChallenger#13]
It is nice to have Pokemon like catching system but It would be nice to have something diferent so here is my sugestion.

By using dialogs you cold convince monsters to travel with you instead of capturing them.
When monster would get under 1/2 of Healt you could talk with them.
Based of Monster type you would get diferent options what to say If you get it correctly you get next dialog round.
then based by if monster is evil or not you would need to get second question right.
Last one could be based on gender.

Example:
First question set
You rock. (Stone)
Do you also like flames (Fire)
etc.

Second question set
I want to conquer world (Evil)
I want to save every monster (Pure)

Third question set
You look wonderfull (Female)
You are powerfull (Male)

Pros:
- Feels more revarding
- Less used
- Monsters would feel like they have some "Personality"
Cons:
- Harder to implement
- More translation work

**Comment by alphaonex86** [comment]
Not for now, too complex and allow infinite retry...
